---
output: md_document
---

COSTmos collates and displays reference data sets on healthcare costs in England.

Current data sets included are:  
- [Drug Tariff](#drug-tariff)  
- [Prescription Cost Analysis](#prescription-cost-analysis)  
- [National Cost Collection](#national-cost-collection)  
- [Unit Costs of Health and Social Care](#unit-costs-of-health-and-social-care)  

COSTmos tries to display the latest version of the data sets. However, we recommend that you go to the original source to verify that this is the case.

Find the code for COSTmos on [GitHub](https://github.com/NICE-Data-and-Analytics/COSTmos).

## Data sets

### Drug Tariff {#drug-tariff}

The [Drug Tariff](https://www.nhsbsa.nhs.uk/pharmacies-gp-practices-and-appliance-contractors/drug-tariff) is produced monthly by the NHS Business Services Authority (NHSBSA) for the Department of Health and Social Care. It "outlines what will be paid to pharmacy contractors for NHS services (reimbursement or remuneration), rules to follow when dispensing, value of the fees and allowances you will be paid, drug and appliance prices you will be paid".

COSTmos sources the following sections of the Drug Tariff from the web pages below:

| Section (link to source) | Description |
|-----------------------------|-------------------------------------------|
| [Part VIIIA](https://www.nhsbsa.nhs.uk/pharmacies-gp-practices-and-appliance-contractors/drug-tariff/drug-tariff-part-viii) | Basic Prices of Drugs |
| [Part VIIIB](https://www.nhsbsa.nhs.uk/pharmacies-gp-practices-and-appliance-contractors/drug-tariff/drug-tariff-part-viii) | Arrangements for payment for Specials and Imported Unlicensed Medicines with a Price Per Unit Above a Minimum Quantity |
| [Part VIIID](https://www.nhsbsa.nhs.uk/pharmacies-gp-practices-and-appliance-contractors/drug-tariff/drug-tariff-part-viii) | Arrangements for payment for Specials & Imported Unlicensed Medicines with Prices Determined Relative to a Commonly Identified Pack Size |
| [Part IX](https://www.nhsbsa.nhs.uk/pharmacies-gp-practices-and-appliance-contractors/drug-tariff/drug-tariff-part-ix) | Appliances |

### Prescription Cost Analysis {#prescription-cost-analysis}

The [Prescription Cost Analysis](https://www.nhsbsa.nhs.uk/statistical-collections/prescription-cost-analysis-england) (PCA) is produced by the NHSBSA and "provides details of the number of items and the Net Ingredient Cost (NIC) of all prescriptions dispensed in the community in England".

### National Cost Collection {#national-cost-collection}

The [National Cost Collection](https://www.england.nhs.uk/costing-in-the-nhs/national-cost-collection/) reports the national average unit cost and total cost for defined services provided to NHS patients across NHS providers, per financial year.

### Unit Costs of Health and Social Care {#unit-costs-of-health-and-social-care}

The [Unit Costs of Health and Social Care manual](https://research.kent.ac.uk/corec/unit-costs-2022-2027/) is published annually and estimates the unit cost of the delivery of health and social care services. COSTmos only extracts the estimates for costs per working hour and training costs for various healthcare professionals. The manual is produced by the Care and Outcomes Research Centre (COReC; formerly known as the Personal Social Services Research Unit, PSSRU) at the University of Kent and the Centre for Health Economics (CHE) at the University of York.



## References

```{r, child=c(find_package_root_file("inst", "references.Rmd"))}
```
    
